create table if not exists public.lista_monitoramento (
  id bigint generated by default as identity primary key,
  nome_solicitado text not null,
  nome_confirmado text not null,
  nome_normalizado text not null unique,
  imo text,
  ativo boolean not null default true,
  adicionado_por text not null,
  adicionado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create table if not exists public.administradores_chat (
  id bigint generated by default as identity primary key,
  telefone text not null unique check (telefone ~ '^[0-9]{10,15}$'),
  ativo boolean not null default true,
  criado_em timestamptz not null default now()
);

create table if not exists public.destinatarios_relatorio (
  id bigint generated by default as identity primary key,
  telefone text not null unique check (telefone ~ '^[0-9]{10,15}$'),
  ativo boolean not null default true,
  inscrito_em timestamptz not null default now(),
  cancelado_em timestamptz
);

create table if not exists public.confirmacoes_chat (
  telefone text primary key check (telefone ~ '^[0-9]{10,15}$'),
  acao text not null check (acao in ('remover_navios')),
  payload jsonb not null,
  criado_em timestamptz not null default now(),
  expira_em timestamptz not null
);

alter table public.navios_monitorados
  add column if not exists lista_monitoramento_id bigint
    references public.lista_monitoramento(id) on delete cascade;

create unique index if not exists navios_monitorados_lista_id_idx
  on public.navios_monitorados(lista_monitoramento_id)
  where lista_monitoramento_id is not null;

alter table public.coletas_monitoramento
  add column if not exists navios_acompanhados integer not null default 0,
  add column if not exists registros_painel integer not null default 0,
  add column if not exists navios_desatualizados integer not null default 0,
  add column if not exists navios_indisponiveis integer not null default 0;

alter table public.lista_monitoramento enable row level security;
alter table public.administradores_chat enable row level security;
alter table public.destinatarios_relatorio enable row level security;
alter table public.confirmacoes_chat enable row level security;
alter table public.navios_monitorados enable row level security;
alter table public.coletas_monitoramento enable row level security;

revoke all on table public.lista_monitoramento from anon, authenticated;
revoke all on table public.administradores_chat from anon, authenticated;
revoke all on table public.destinatarios_relatorio from anon, authenticated;
revoke all on table public.confirmacoes_chat from anon, authenticated;
revoke all on table public.navios_monitorados from anon, authenticated;
revoke all on table public.coletas_monitoramento from anon, authenticated;

grant all on table public.lista_monitoramento to service_role;
grant all on table public.administradores_chat to service_role;
grant all on table public.destinatarios_relatorio to service_role;
grant all on table public.confirmacoes_chat to service_role;
grant all on table public.navios_monitorados to service_role;
grant all on table public.coletas_monitoramento to service_role;
grant usage, select on all sequences in schema public to service_role;

comment on table public.lista_monitoramento is
  'Lista unica e permanente dos navios acompanhados pela equipe.';
comment on table public.administradores_chat is
  'Numeros autorizados a adicionar ou remover navios pelo chat.';
comment on table public.destinatarios_relatorio is
  'Numeros inscritos para receber o relatorio horario agrupado.';
comment on table public.confirmacoes_chat is
  'Operacoes destrutivas aguardando confirmacao do administrador.';
