alter table public.navios_monitorados
  add column if not exists ultima_consulta timestamptz,
  add column if not exists ultima_alteracao timestamptz,
  add column if not exists situacao text not null default 'indisponivel',
  add column if not exists ausencias_consecutivas integer not null default 0;

-- O painel atual nem sempre publica IMO e ETA para todos os navios.
alter table public.navios_monitorados
  alter column imo drop not null,
  alter column eta drop not null;

alter table public.navios_monitorados
  drop constraint if exists navios_monitorados_situacao_check;

alter table public.navios_monitorados
  add constraint navios_monitorados_situacao_check
  check (situacao in ('atualizado', 'desatualizado', 'indisponivel'));

alter table public.navios_monitorados
  drop constraint if exists navios_monitorados_ausencias_check;

alter table public.navios_monitorados
  add constraint navios_monitorados_ausencias_check
  check (ausencias_consecutivas >= 0);

create index if not exists navios_monitorados_nome_idx
  on public.navios_monitorados (lower(nome));

create index if not exists navios_monitorados_imo_idx
  on public.navios_monitorados (imo);

create table if not exists public.coletas_monitoramento (
  id bigint generated by default as identity primary key,
  inicio timestamptz not null,
  fim timestamptz not null,
  resultado text not null check (resultado in ('sucesso', 'erro')),
  navios_encontrados integer not null default 0,
  navios_incluidos integer not null default 0,
  navios_atualizados integer not null default 0,
  navios_removidos integer not null default 0,
  mensagem_erro text
);

comment on column public.navios_monitorados.ultima_consulta is
  'Ultima coleta valida em que o navio foi localizado no painel.';
comment on column public.navios_monitorados.ultima_alteracao is
  'Ultima mudanca de ETA, ETB, local ou evento.';
comment on column public.navios_monitorados.ausencias_consecutivas is
  'Quantidade de coletas validas consecutivas sem localizar o navio.';
comment on table public.coletas_monitoramento is
  'Resumo operacional de cada tentativa de sincronizacao do painel.';
